- hosts: all
  remote_user: vagrant
  become: yes

  tasks:
    - name: Yum update all
      yum: 
        name: '*'
        state: latest

    - name: install httpd/mod_auth_openidc
      yum: 
        name: 
          - httpd
          - mod_auth_openidc
        state: latest

    - name: start httpd
      service: 
        name: httpd
        state: restarted
        